App\Entity\Measurement:
  properties:
    celsius:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -100
          max: 100
          groups: ['create', 'edit']
          notInRangeMessage: 'Temperature must be between -100 and 100°C.'
    humidity:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: 0
          max: 100
          groups: ['create', 'edit']
          notInRangeMessage: 'Humidity must be between 0% and 100%.'
    cloudcover:
      - NotBlank:
          groups: ['create', 'edit']
      - Choice:
          choices: ['Very Cloudy', 'Cloudy', 'Partly Cloudy', 'No Clouds']
          message: 'Choose a valid cloud cover.'
          groups: ['create', 'edit']
    date:
      - NotBlank:
          groups: ["create", "edit"]
      - Type:
          type: \DateTimeInterface
          message: "Date must be valid."
    location:
      - NotBlank:
          groups: ['create', 'edit']
      - Valid:
          groups: ['create', 'edit']

App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
      - Length:
          min: 2
          max: 100
          groups: ['create', 'edit']
    country:
      - NotBlank:
          groups: ['create', 'edit']
      - Choice:
          choices: ['PL', 'DE', 'FR', 'ES', 'IT', 'GB', 'US']
          message: "Please select a valid country."
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          groups: ['create']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          groups: ['create']
      - Range:
          min: -180
          max: 180
          groups: ['create', 'edit']